import numpy as np

RUN_TIME = 60 * 60
THREADS = 8
OPTIMIZERS = 2
N_STEP_RETURN = 8
GAMMA = 0.99
GAMMA_N = GAMMA ** N_STEP_RETURN
NUM_STATE = 6 * 7
NUM_ACTIONS = 7
LOSS_V = .5  # v loss coefficient
LOSS_ENTROPY = .01  # entropy coefficient
MIN_BATCH = 32
NONE_STATE = np.zeros(NUM_STATE)
EPS_START = 0.4
EPS_STOP = .15
EPS_STEPS = 75000
THREAD_DELAY = 0.001